local icons = {
  arrow_open = "",
  arrow_closed = "",
  class = '',
  color = '',
  constant = '',
  constructor = '',
  enum = '↓',
  enum_member = '',
  event = '',
  field = 'ﴲ',
  function_fn = '',
  lightbulb = '',
  information = '',
  interface = 'ﰮ',
  keyword = '',
  method = '',
  module = '',
  modified = '*',
  operator = '',
  property = '⊡',
  reference = '',
  snippet = '﬌',
  struct = 'ﳤ',
  text = '',
  type_parameter = '',
  unit = '',
  value = '',
  variable = '',
  vcs = {
    unstaged = "±",
    staged = "◉",
    unmerged = "",
    renamed = "➜",
    untracked = "◍",
    deleted = "",
    ignored = "◌"
  },
  file = {
    default = '',
    symlink = '',
  },
  folder = {
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
  diagnostics = {
    hint = "",
    info = "",
    warning = "",
    error = "",
  }
}

return icons
