local icons = {
  arrow_open = "",
  arrow_closed = "",
  lightbulb = '',
  modified = '*',
  vcs = {
    unstaged = "±",
    staged = "✓",
    unmerged = "",
    renamed = "➜",
    untracked = "?",
    deleted = "×",
    ignored = "◌"
  },
  file = {
    default = '',
    symlink = '',
  },
  folder = {
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
  diagnostics = {
    hint = "",
    info = "",
    warning = "",
    error = "",
  },
  symbols = {
    array = '',
    boolean = 'в',
    class = 'ﴯ',
    color = '',
    constant = '',
    constructor = '',
    enum = '',
    enum_member = '',
    event = '',
    field = '',
    function_fn = 'ƒ',
    interface = '',
    keyword = '',
    method = '',
    module = '',
    namespace = '',
    number = 'ɴ',
    null = '∅',
    object = '',
    operator = '',
    package = '',
    property = 'ﰠ',
    reference = '',
    snippet = "",
    struct = 'פּ',
    string = '',
    text = "",
    type_parameter = '',
    unit = '',
    value = '⃨⃨⃨',
    variable = '',
  }
}

return icons
