local icons = {
  Class = '',
  Color = '',
  Constant = '',
  Constructor = '',
  Enum = '↓',
  EnumMember = '',
  Error = '',
  Event = '',
  Field = 'ﴲ',
  File = '',
  Folder = '',
  Function = '',
  Hint = '',
  Information = '',
  Interface = 'ﰮ',
  Keyword = '',
  Method = '',
  Module = '',
  Operator = '',
  Property = '⊡',
  Reference = '',
  Snippet = '﬌',
  Struct = 'ﳤ',
  Text = '',
  TypeParameter = '',
  Unit = '',
  Value = '',
  Variable = '',
  Warning = '',
}

return icons
