-- Plugins
require('plugins.bufferline')
require('plugins.compe')
require('plugins.gitsigns')
require('plugins.illuminate')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.luasnip')
require('plugins.numb')
require('plugins.startify')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.tree')
require('plugins.trouble')
require('plugins.treesitter')
require('plugins.zen-mode')

